- project:
    name: openstack/pyeclib
    experimental:
      jobs:
        - pyeclib-tox-py27-centos-7
        - libec-pyeclib-unit-centos-7
        - libec-pyeclib-unit

- job:
    name: pyeclib-tox-py27-centos-7
    parent: legacy-base
    run: playbooks/legacy/pyeclib-tox-py27-centos-7/run
    post-run: playbooks/legacy/pyeclib-tox-py27-centos-7/post
    timeout: 2400
    nodeset: legacy-centos-7
    required-projects:
      - openstack/requirements

- job:
    name: libec-pyeclib-unit-centos-7
    parent: legacy-base
    run: playbooks/legacy/libec-pyeclib-unit-centos-7/run
    timeout: 1800
    nodeset: legacy-centos-7
    required-projects:
      - openstack/liberasurecode
      - openstack/pyeclib

- job:
    name: libec-pyeclib-unit
    parent: legacy-base
    run: playbooks/legacy/libec-pyeclib-unit/run
    timeout: 1800
    required-projects:
      - openstack/liberasurecode
      - openstack/pyeclib
